services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=victor-borzaquel-store'
      - 'POSTGRES_PASSWORD=docker'
      - 'POSTGRES_USER=docker'
    ports:
      - '5432:5432'
