server:
  port: 8080
spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://postgres:5432/victor-borzaquel-store
#    username: docker
#    password: docker
  datasource:
    url: jdbc:h2:mem:a1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
